import psycopg2
DB = dict(host='aws-0-ap-southeast-1.pooler.supabase.com', port=6543, dbname='postgres', user='postgres.fqznwnoesagaxrbyxdxx', password='shanusupabase', sslmode='require', connect_timeout=15)
conn = psycopg2.connect(**DB)
cur = conn.cursor()
cur.execute("SELECT p.proname, pg_get_function_identity_arguments(p.oid), pg_get_functiondef(p.oid) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname='public' AND p.proname IN ('is_org_member','is_org_admin')")
for r in cur.fetchall():
    print("FUNC:", r[0], "(", r[1], ")")
    print(r[2])
print("\n=== ORG_MEMBERS COLUMNS ===")
cur.execute("SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='organization_members' ORDER BY ordinal_position")
for r in cur.fetchall(): print(f"  {r[0]}: {r[1]} (null:{r[2]})")
print("\n=== ORGANIZATIONS COLUMNS ===")
cur.execute("SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='organizations' ORDER BY ordinal_position")
for r in cur.fetchall(): print(f"  {r[0]}: {r[1]} (null:{r[2]})")
print("\n=== RLS STATUS ===")
cur.execute("SELECT tablename, rowsecurity FROM pg_tables WHERE schemaname='public' AND tablename IN ('organizations','organization_members','profiles','user_settings')")
for r in cur.fetchall(): print(f"  {r[0]}: RLS={'ON' if r[1] else 'OFF'}")
print("\n=== TRIGGERS ===")
cur.execute("SELECT trigger_name, event_manipulation, event_object_table FROM information_schema.triggers WHERE trigger_schema='public' AND event_object_table IN ('organizations','organization_members','profiles')")
for r in cur.fetchall(): print(f"  {r[0]} ON {r[2]} ({r[1]})")
print("\n=== AUTH USERS ===")
cur.execute("SELECT id, email FROM auth.users LIMIT 5")
for r in cur.fetchall(): print(f"  {r[0]} | {r[1]}")
print("\n=== ORGANIZATIONS ===")
cur.execute("SELECT id, name, owner_id FROM public.organizations LIMIT 5")
for r in cur.fetchall(): print(f"  {r[0]} | {r[1]} | owner: {r[2]}")
print("\n=== MEMBERSHIPS ===")
cur.execute("SELECT id, organization_id, user_id, role FROM public.organization_members LIMIT 5")
for r in cur.fetchall(): print(f"  {r[0]} | org: {r[1]} | user: {r[2]} | role: {r[3]}")
conn.close()
