import os

lines = []
lines.append('import type { FeatureId } from "@/features/entitlement";')
lines.append("")
lines.append("export interface NavItem {")
lines.append("  label: string;")
lines.append("  href: string;")
lines.append("  icon: string;")
lines.append("  disabled?: boolean;")
lines.append("  featureId?: FeatureId;")
lines.append("}")
lines.append("")
lines.append("export interface NavGroup {")
lines.append("  label: string;")
lines.append("  items: NavItem[];")
lines.append("}")
lines.append("")
lines.append("export const NAV_GROUPS: NavGroup[] = [")
lines.append("  {")
lines.append('    label: "Main",')
lines.append("    items: [")
lines.append('      { label: "Dashboard", href: "/dashboard", icon: "dashboard", featureId: "dashboard" },')
lines.append('      { label: "Intelligence", href: "/dashboard/intelligence", icon: "intelligence", featureId: "company_research" },')
lines.append('      { label: "Prospects", href: "/dashboard/prospects", icon: "prospects", featureId: "prospects" },')
lines.append('      { label: "Saved Lists", href: "/dashboard/saved-lists", icon: "lists", featureId: "saved_lists" },')
lines.append('      { label: "Analytics", href: "/dashboard/analytics", icon: "analytics", featureId: "advanced_analytics" },')
lines.append('      { label: "Automation", href: "/dashboard/automation", icon: "automation", featureId: "automation" },')
lines.append('      { label: "Import", href: "/dashboard/import", icon: "import", featureId: "import" },')
lines.append('      { label: "Export", href: "/dashboard/export", icon: "export", featureId: "export" },')
lines.append("    ],")
lines.append("  },")
lines.append("  {")
lines.append('    label: "Team",')
lines.append("    items: [")
lines.append('      { label: "Team Dashboard", href: "/dashboard/team", icon: "members", featureId: "team_collaboration" },')
lines.append('      { label: "Notifications", href: "/dashboard/notifications", icon: "bell" },')
lines.append("    ],")
lines.append("  },")
lines.append("  {")
lines.append('    label: "Workspace",')
lines.append("    items: [")
lines.append('      { label: "Organization", href: "/dashboard/organization", icon: "organization" },')
lines.append('      { label: "Billing", href: "/dashboard/billing", icon: "billing" },')
lines.append('      { label: "Integrations", href: "/dashboard/integrations", icon: "integrations" },')
lines.append("    ],")
lines.append("  },")
lines.append("  {")
lines.append('    label: "Settings",')
lines.append("    items: [")
lines.append('      { label: "Settings", href: "/dashboard/settings", icon: "settings" },')
lines.append('      { label: "Help", href: "/dashboard/help", icon: "help" },')
lines.append("    ],")
lines.append("  },")
lines.append("];")
lines.append("")

content = "\n".join(lines)
path = os.path.join("src", "components", "dashboard", "navigation", "config.ts")
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("written", len(content), "bytes")